### ISSUE TITLE
help with config.json

### ISSUE THREAD

**Issue by jwrl7** [ci-dashboard/gitlab-ci-dashboard#14]
Im looking for a bit of guidance for writing a config.json

Im currently receiving the following error when navigating to the local web page. 

`nvidia@tegra-ubuntu:~/gitlab-dash/node_modules/gitlab-ci-dashboard/bin$ ./gitlab-ci-dashboard --config ../config/dashboard_config.json 
The dashboard is now available at http://localhost:8081/?standalone=true
(node:20910) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/nvidia/gitlab-dash/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

My config looks something like this:

```
{
"dashboard": {
    "config": {
      "gitlab": "gitlab.com",
      "token": "blablabla",
      "gitlabciProtocol": "ssh", # i also tried https
      "hideSuccessCards": false,
      "hideVersion": false,
      "interval": 60,
      "apiVersion": 4
    },
    "projects": [
      {
        "description": "React Native render for draft.js model",
        "namespace": "myproject_group", #could you clarify what is included in the namespace
        "project": "repo_name", #is this supposed be the project number id?
        "branch": "master"
      }
    ]
  }
}

```

Thanks

**Comment by juanje** [comment]
Same here.
I tried different combinations for the `namespace` and the `project` but nothing. I get the same error.
Could you give some help with this? Maybe an example from the output from the API for projects or something.

Thanks.

**Comment by Markus-St** [comment]
I am getting the same error. Also tried different combinations of namespace and project.

**Comment by devtech0101** [comment]
same error, any resolution for this issue

`(node:18624) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/lib/node_modules/gitlab-ci-dashboard/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
(node:18624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
